sources:
  - type: parquet
    table_name: parquet_table
    file_path: "/path/to/parquet1"
  - type: parquet
    table_name: parquet_table_2
    file_path: "/path/to/parquet2"
  - type: postgres
    table_name: postgres_table
    connection_string: "dbname=tfmv user=postgres password=password host=localhost port=5432"

query:
  join_columns:
    - source: parquet_table
      column: join_col_1
    - source: postgres_table
      column: join_col_2
  select_columns:
    - "col1"
    - "col2"
  sql: |
    SELECT {select_columns}
    FROM {parquet_table} p
    JOIN {postgres_table} pg ON p.{join_col_1} = pg.{join_col_2}
