postgres:
  connection_string: "dbname=tfmv user=postgres password=password host=localhost port=5432"

parquet:
  file_path: "/Users/thomasmcgeehan/ArrowLake/arrowlake/data/nation.parquet"

query:
  parquet_table_name: "parquet_table"
  postgres_table_name: "nations"
  join_column: "n_nationkey"
  select_columns:
    - "n_nationkey"
  query: |
    SELECT count(*)
    FROM parquet_table p
    JOIN postgres_db.nations pg ON p.n_nationkey = pg.n_nationkey
